### ISSUE TITLE
404 pages are not internationalized

### ISSUE THREAD

**Issue by jeanlucaslima** [kslstn/astro-i18n-blog-starter#1]
Expected behavior: 404 pages should follow language preferences. 
What happens: 404 pages default to English

**Comment by jeanlucaslima** [comment]
I think this is an astro issue, looks like Astro doesn't support 404 pages with internationalization. Will open an issue at astro's repo.

**Comment by kslstn** [comment]
Hey Jean Lucas, I don't think there's very much a statically rendered site can do here without JS. If the page is truly static, the server can't provide a different locale based on the user's preference.

What I've done before is:
1. Provide texts in all locales inside a `<noscript>` tag. 
2. Repeat the texts for browsers with JS enabled, use CSS to hide all of them except the one that matches the browser's locale

**Comment by jeanlucaslima** [comment]
I've been talking with some people and it is possible, but it will be specific to each server. For example, it is possible on vercel, but need a custom vercel.json file. This is an Astro limitation nowadays, I will be working further on this.
