### ISSUE TITLE
Dutch navigation broken

### ISSUE THREAD

**Issue by jeanlucaslima** [kslstn/astro-i18n-blog-starter#2]
Dutch navigation doesn't always works, I think it just needs to set up them header for Dutch as well.

**Comment by kslstn** [comment]
I intentionally didn't define a Dutch navigation, to show how it uses the default locale's instead. Do you have an example of where it doesn't do that?

**Comment by jeanlucaslima** [comment]
Oh, ok then. I thought it was broken behavior, not that it was intentional.

**Comment by kslstn** [comment]
Yeah I can see why :) What I tried with this starter is making the threshold to add a new locale really low, so that if someone wants to make just one page in some language, they can do so and use the defaultLocale for everything else.
