### ISSUE TITLE
Header navigation items are in a different language

### ISSUE THREAD

**Issue by luatdolphin** [kslstn/astro-i18n-blog-starter#7]
When I press and [Dutch]-[nl] link it returns the default language, this only seems to happen with the last language in the language list.

**Comment by kslstn** [comment]
Hi, I haven't been able to reproduce that. On what page do you have that issue?

**Comment by luatdolphin** [comment]
On all page. You can check by click to nl language and navigate to another page, you will recognize it

**Comment by kslstn** [comment]
On the homepage of the demo site, both 'Dutch' links have `https://astro-i18n-blog-starter.netlify.app/nl` as their `href`s, pointing to the Dutch version of the homepage. Can you provide a link to a page on the demo site where the behavior is off?

**Comment by luatdolphin** [comment]
For example, when you open this link https://astro-i18n-blog-starter.netlify.app/nl/onderwerp/
and then click to another page such as [About] on navigation, it will change to https://astro-i18n-blog-starter.netlify.app/about instead https://astro-i18n-blog-starter.netlify.app/nl/over/

**Comment by kslstn** [comment]
This is desired behavior 😅 I've added feature 2 to the readme to clarify:
> Allow adding pages for a new locale with minimal effort; use the default locale* as a fallback for missing settings and strings.
> 
> *) This is why the Dutch demo pages have an English header menu; no Dutch menu items were defined.

And a comment to the [Header component](https://github.com/kslstn/astro-i18n-blog-starter/blob/main/src/components/Header.astro):

> If no items are available for the page's locale, the items for the defaultLocale will be used
